services:
  - type: web
    name: test-runner
    env: python
    buildCommand: |
      python -m pip install -r requirements.txt
      npm install
      npm install mocha --save-dev
      npm install chromedriver --save-dev
      npm install -g chromedriver
      python setup.py
    startCommand: python sel_runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 23.10.0